Bloggie.Web/Models/Domain/BlogPost.cs
namespace Bloggie.Web.Models.Domain
{
    public class BlogPost
    {
        //prop   /ctor
        public Guid Id { get; set; }  // Guid --> unique identifer
        public string Heading { get; set; }
        public string PageTitle { get; set; }
        public string Content { get; set; }
        public string ShortDescription { get; set; }
        public string FeaturedImageUrl { get; set; }
        public string UrlHandle { get; set; }
        public DateTime PublishedDate { get; set; }
        public string Author { get; set; }
        public bool Visible { get; set; }

        //show many to many relationship
        public ICollection<Tag> Tags{ get; set; }  //1 blog having many tags

    }
}

Bloggie.Web/Models/Domain/Tag.cs
namespace Bloggie.Web.Models.Domain
{
    public class Tag
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }

        //many to many relation between blogpost and tag
        public ICollection<BlogPost> BlogPosts { get; set; }  // 1 tag have multiple blogpost
    }
}

Bloggie.Web/Models/ErrorViewModel.cs
namespace Bloggie.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Bloggie.Web/Models/Event.cs
namespace Bloggie.Web.Models
{
    public class Event
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string StartDate { get; set; }
    }
}

Bloggie.Web/Models/ViewModels/AddTagRequest.cs
namespace Bloggie.Web.Models.ViewModels
{
    public class AddTagRequest
    {
        public string Name { get; set; }
        public string DisplayName { get; set; }

    }
}

Bloggie.Web/Controllers/AdminTagsController.cs
using Bloggie.Web.Data;
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Bloggie.Web.Controllers
{
    public class AdminTagsController : Controller
    {
        private readonly BloggieDbContext _bloggieDbContext;
        
        //constructor injection  --> using service to inject bloggiedbcontext
        public AdminTagsController(BloggieDbContext bloggieDbContext)
        {
            _bloggieDbContext = bloggieDbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(AddTagRequest addTagRequest)
        {
            //Mapping the AddTagRequest model to Tag Domain model
            var tag = new Tag
            {
                Name = addTagRequest.Name,
                DisplayName = addTagRequest.DisplayName
            };
            _bloggieDbContext.Tags.Add(tag);
            _bloggieDbContext.SaveChanges();
            return View("Add");
        }

        [HttpGet]
        public IActionResult Delete()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Delete(AddTagRequest addTagRequest)
        {
            //Mapping the AddTagRequest model to Tag Domain model
            var tag = new Tag
            {
                Name = addTagRequest.Name,
                DisplayName = addTagRequest.DisplayName
            };
            _bloggieDbContext.Tags.Remove(tag);
            _bloggieDbContext.SaveChanges();
            return View("Add");
        }
    }
}

Bloggie.Web/Controllers/HomeController.cs
using Bloggie.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Bloggie.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Event()
        {
            return View();
        }
        public IActionResult Calendar(Event obj)
        {
            ViewData["events"] = new[]
            {
                //new Event{
                //    Id = obj.Id ,
                //    Title = obj.Title,
                //    StartDate = obj.StartDate
                //} 
                new Event{ Id = 1, Title = "Preparation", StartDate = "2023-09-12"},
            };
           // List<Event> events = new List<Event>();
            //events.Add(obj);
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Bloggie.Web/Views/AdminTags/Add.cshtml
@model Bloggie.Web.Models.ViewModels.AddTagRequest
@{

}
<div bg-secondary bg-opacity-10 py-2>
    <div class="container">
        <h1>Add New Tag</h1>
    </div>
</div>

<div class="container" py-5>
    <form method="post">
        <div class="mb-3">
            <label class="form-label" >Name</label>
            <input type ="text" class="form-control" id="name" asp-for="Name"/>
        </div>
        <div class="mb-3">
            <label class="form-label">Display Name</label>
            <input type="text" class="form-control" id="displayName" asp-for="DisplayName"/>
        </div>
        <div class="mb-3">
            <button type ="submit" class="btn btn-dark">Submit</button>
        </div>
        @* when submitted then the AddTagRequest model is captured inside the AdminTagsController Post method *@
    </form>
</div>

Bloggie.Web/Views/AdminTags/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

Bloggie.Web/Views/AdminTags/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

Bloggie.Web/Views/Home/Calendar.cshtml
@model IEnumerable<Event>

@{
    ViewData["Title"] = "Calendar";

    var events = (IEnumerable<Event>)ViewData["events"];
    var length = events.Count();
}

<table id="todoTable">
    @for (int i = 0; i < length; i++)
    {
        <tr>
            <td>@Html.Encode(events.ElementAt(i).Id )</td>
            <td>@Html.Encode(events.ElementAt(i).Title)</td>
            <td>@Html.Encode(events.ElementAt(i).StartDate)</td>
        </tr>
    }
</table>


<div class="calendarContainer">
    <div class="mb-3">
        <form asp-controller="Home" asp-action="Event">
            <button type="submit" class="btn btn-dark">Add New Event</button>
        </form>
    </div>
    <div id="calendar"></div>
</div>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.1.0/main.min.css">
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.1.0/main.min.js"></script>

<script>
    let eventsArr = loadData();
    let calendar = initCalendar();

    function loadData() {
        let eventsArr = [];

        let todoTable = document.getElementById("todoTable");
        let trElem = todoTable.getElementsByTagName("tr");
        console.log(trElem);
        for (let tr of trElem) {
            console.log(tr);
            let tdElems = tr.getElementsByTagName("td");
            let eventObj = {
                id: tdElems[0].innerText,
                title: tdElems[1].innerText,
                start: tdElems[2].innerText,
            }

            eventsArr.push(eventObj);
        }

        return eventsArr;
    }

    function initCalendar() {
        var calendarEl = document.getElementById('calendar');

        let calendar = new FullCalendar.Calendar(calendarEl, {
            initialView: 'dayGridMonth',
            headerToolbar: {
                left: 'prev,next today',
                center: 'title',
                right: 'dayGridMonth,timeGridWeek,timeGridDay'
            },
            events: eventsArr,
        });

        calendar.render();

        return calendar;
    }
</script>

Bloggie.Web/Views/Home/Event.cshtml
@model IEnumerable<Event>

@{
    ViewData["Title"] = "Events";
}

<h1>Add New Event</h1>


<div class="container" py-5>
    <form method="post" asp-controller="Home" asp-action="Calendar">
        <div class="mb-3">
            <label class="form-label">Title</label>
            <input type="text" class="form-control" id="name" style="width: 220px "/>
        </div>
        <div class="mb-3">
            <label class="form-label">Date</label>
            <input type="date" class="form-control" id="date" style="width: 220px "/>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-dark">Save</button>
            <a asp-controller="Home" asp-action="Calendar" class=" btn btn-secondary" style="width: 150px">Back to Calendar </a>
        </div>
    </form>
</div>

Bloggie.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Bloggie.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bloggie.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bloggie.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bloggie.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Calendar">Calendar</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Admin
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="AdminTags" asp-action="Add">Add Tag</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Bloggie.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>